### ISSUE TITLE
User becomes undefined when closing second edstem tab

### ISSUE THREAD

**Issue by pokir** [polysource-projects/edstem-splited#5]
## Bug description

The user in the online users list shows as "undefined" after closing a second edstem browser tab.

<img width="155" alt="undefined user" src="https://github.com/polysource-projects/edstem-splited/assets/80112484/6f51a932-ac61-429f-8989-bb021134e939">

## Steps to reproduce

1. Open a browser tab and go to https://edstem.org/
2. Open a second browser tab and go to https://edstem.org/
3. Choose a course to see the online users list
4. Close the first tab
5. See bug in users list

**Comment by pokir** [comment]
fixed by 7a552eaa329246bf69167aff76d1b2eb87c35481

**Comment by Androz2091** [comment]
Maybe not actually I can still see some undefined + userscript seems to be broken on my mobile phone 🤔
